/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/app/AppFooter.vue')['default']
    AppTopbar: typeof import('./components/app/AppTopbar.vue')['default']
    OpenVueData: typeof import('./components/demo/OpenVueData.vue')['default']
    OpenVueInput: typeof import('./components/demo/OpenVueInput.vue')['default']
    OpenVueLabel: typeof import('./components/demo/OpenVueLabel.vue')['default']
    OpenVueOutput: typeof import('./components/demo/OpenVueOutput.vue')['default']
    OpenVueSchemaEditor: typeof import('./components/demo/OpenVueSchemaEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
