import {
  formAutoCompleteDefinition,
  formCascadeSelectDefinition,
  formCheckboxDefinition,
  formColorPickerDefinition,
  formDatePickerDefinition,
  formInputMaskDefinition,
  formInputNumberDefinition,
  formInputOtpDefinition,
  formInputTextDefinition,
  formKnobDefinition,
  formListboxDefinition,
  formMultiSelectDefinition,
  formPasswordDefinition,
  formRadioButtonDefinition,
  formRatingDefinition,
  formSelectButtonDefinition,
  formSelectDefinition,
  formSliderDefinition,
  formTextareaDefinition,
  formToggleButtonDefinition,
  formToggleSwitchDefinition,
  formTreeSelectDefinition,
} from './input'

import {
  formOutputBooleanDefinition,
  formOutputDateDefinition,
  formOutputDurationDefinition,
  formOutputLinkDefinition,
  formOutputListDefinition,
  formOutputNumberDefinition,
  formOutputReferenceDefinition,
  formOutputTextDefinition,
} from './output'

import { formRepeaterDefinition } from './repeater'

export const formInputs = {
  formAutoComplete: formAutoCompleteDefinition,
  formInputText: formInputTextDefinition,
  formInputNumber: formInputNumberDefinition,
  formInputMask: formInputMaskDefinition,
  formPassword: formPasswordDefinition,
  formCheckbox: formCheckboxDefinition,
  formToggleSwitch: formToggleSwitchDefinition,
  formTextarea: formTextareaDefinition,
  formSelect: formSelectDefinition,
  formMultiSelect: formMultiSelectDefinition,
  formDatePicker: formDatePickerDefinition,
  formSlider: formSliderDefinition,
  formKnob: formKnobDefinition,
  formRating: formRatingDefinition,
  formRadioButton: formRadioButtonDefinition,
  formColorPicker: formColorPickerDefinition,
  formToggleButton: formToggleButtonDefinition,
  formListbox: formListboxDefinition,
  formSelectButton: formSelectButtonDefinition,
  formCascadeSelect: formCascadeSelectDefinition,
  formTreeSelect: formTreeSelectDefinition,
  formInputOtp: formInputOtpDefinition,
  formRepeater: formRepeaterDefinition,
}

export const formOutputs = {
  formOutputText: formOutputTextDefinition,
  formOutputLink: formOutputLinkDefinition,
  formOutputReference: formOutputReferenceDefinition,
  formOutputNumber: formOutputNumberDefinition,
  formOutputDate: formOutputDateDefinition,
  formOutputBoolean: formOutputBooleanDefinition,
  formOutputDuration: formOutputDurationDefinition,
  formOutputList: formOutputListDefinition,
}
